# Generated by Django 6.0 on 2025-12-08 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='applicationhistory',
            old_name='timestamp',
            new_name='changed_at',
        ),
        migrations.RenameField(
            model_name='applicationhistory',
            old_name='new_stage',
            new_name='from_stage',
        ),
        migrations.RenameField(
            model_name='applicationhistory',
            old_name='previous_stage',
            new_name='to_stage',
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
