# Generated by Django 6.0 on 2025-12-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_user_company_application_unique_candidate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
